debug: false
#
# 数据库设置，选择你需要使用的数据储存方式，sqlite,mysql
# 默认: sqlite
data_storage:
  use_type: sqlite
  mysql:
    host: '127.0.0.1'
    port: 3306
    database: 'server_mail'
    username: 'root'
    password: '123456'
    params: '?autoReconnect=true&useSSL=false'
  hikari_settings:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
Redis:
  # 是否启用 Redis 用作跨服发送，如果不启用，默认使用插件通道。
  use: false
  host: 127.0.0.1
  port: 6379
  password:
  ssl: false

# 邮件过期时间，如果永不过期 = -1
expiryTimer: 2d

# 物品邮件 物品预览使用 lore 展示 (只限 1.17+)
useBundle: false

# 附件信息展示方法
# 请注意，分割务必使用 ; 符号
mailDisAppend: "§f{0} §7* §f{1} ;"


# 特殊的语言文件，在带有过多物品时显示
mailDisMiss: "§7剩余 §6{0} §7项未显示..."


# 种类翻译
# 部分短词的翻译，以适应不同的语言环境
typeTranslate:
  混合邮件: "&e混合类型"
  # 混合邮件: "&e Normal"
  纯文本: "&f纯文本"
  # 纯文本: "&f text"
  已提取: "&a已领取"
  # 已提取: "&a Acquired"
  未提取: "&f未领取"
  # 未提取: "&f NotObtained"
  系统: "&9系统"
  # 系统: "&9 system"


# 对玩家输入的字符串进行匹配检查
# 放置一部分注入，以及敏感词, 建议以正则表达式为主，以提供检查性能
# 支持正则表达式
inputCheck:
  # 本地词库
  local:
    - "腐竹傻逼"
    - "傻逼"
    - '[\s\S]*中国[\s\S]*'
  # 云词库
  cloud:
  # - "https://raw.githubusercontent.com/Yurinann/Filter-Thesaurus-Cloud/main/database.json"
# 云词库需要的 JSON 格式
# 或者通过API自行注册新正则
#  {
#    "words": [
#      "fuck",
#      "fucku",
#      "nmsl"
#    ]
#  }